name: cifar10-resnet18-ID-random
method: grid
parameters:
  intrinsic_dim:
    values:
      - 250000
      - 100000
      - 50000
      - 25000
      - 12000
      - 10000
      - 7500
      - 5000
      - 2500
      - 1000
  base_width:
    values:
      - 64
      - 32
      - 16
      - 8
      - 4
      - 2
      - 1
  label_noise:
    values:
      - 1.
  intrinsic_mode:
    values:
      - rdkron
program: experiments/train.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --dataset=cifar10
  - --model-name=resnet18k
  - --optimizer=adam
  - --epochs=500
  - --lr=1e-3
  - ${args}
