name: ti-efficientnet_b0-datadep
method: grid
parameters:
  intrinsic_dim:
    values:
      - -1
      - 5000
      - 10000
      - 15000
      - 20000
      - 50000
  train_subset:
    values:
      - .2
      - .5
      - .8
program: experiments/train_dd_priors.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --seed=137
  - --dataset=tiny-imagenet
  - --model-name=efficientnet_b0
  - --optimizer=adam
  - --epochs=100
  - --lr=1e-3
  - --intrinsic-mode=filmrdkron
  - --indices-path=/scratch/sk6876/assets/pactl/ddp-idx/indices_tiny-imagenet_137.npy
  - ${args}
