name: fmnist-resnet20-ID
method: grid
parameters:
  intrinsic_dim:
    values:
      - -1
      - 250000
      - 100000
      - 50000
      - 25000
      - 12000
      - 10000
      - 7500
      - 5000
      - 2500
      - 1000
  intrinsic_mode:
    values:
      - rdkron
  seed:
    values:
      - 137
program: experiments/train.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --dataset=fmnist
  - --model-name=resnet20
  - --base-width=16
  - --optimizer=adam
  - --epochs=500
  - --lr=1e-3
  - ${args}
