name: transfer-cifar10-fmnist-resnet20-ID-bound
method: grid
parameters:
  prenet_cfg_path:
    values:
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220503-qkl0w40w/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220503-gzo5e6v8/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220503-bikwgwzl/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220503-x5tsug3v/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220503-aioy6msy/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220503-6prfmcxs/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220503-yzxuklp4/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220502-gp21jssx/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220502-jak7cou7/files/net.cfg.yml
      - /data/sanyam_s/assets/pactl/sweep-bu6bb4px/run-20220502-6wh95170/files/net.cfg.yml
  use_kmeans:
    values:
      - False
      - True
  levels:
    values:
      - 20
      - 50
      - 10
      - 100
  scale_posterior:
    values:
      - 1e-3
      - 5e-3
      - 1e-2
      - 5e-2
  rescale_posterior:
    values:
      - True
      - False
  quant_epochs:
    values:
      - 0
      - 20
  misc_extra_bits:  ## Penalty for grid search.
    values:
      - 10
program: experiments/compute_bound.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --dataset=fmnist
  - --encoding-type=arithmetic
  - ${args}
